# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('ident', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleJumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.Advertisement')),
                ('size', models.IntegerField()),
                ('bicycle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_type', to='advertisement.BicycleType')),
                ('jumper_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_back', to='advertisement.BicycleJumper')),
                ('jumper_front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_front', to='advertisement.BicycleJumper')),
            ],
            bases=('advertisement.advertisement',),
        ),
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.Advertisement')),
                ('size', models.IntegerField()),
                ('for_weight', models.IntegerField(blank=True)),
                ('ski_type', models.CharField(choices=[(b'classic', b'\xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5'), (b'skate', b'\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8c\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb5'), (b'children', b'\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5')], max_length=20)),
            ],
            bases=('advertisement.advertisement',),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
