# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 14:42
from __future__ import unicode_literals

import advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('ident', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='BicycleJumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=advertisement.models.get_image_filename, verbose_name=b'Image')),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.Advertisement')),
                ('size', models.IntegerField()),
                ('bicycle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_type', to='advertisement.BicycleType')),
                ('jumper_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_back', to='advertisement.BicycleJumper')),
                ('jumper_front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_front', to='advertisement.BicycleJumper')),
            ],
            bases=('advertisement.advertisement',),
        ),
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.Advertisement')),
                ('size', models.IntegerField()),
                ('for_weight', models.IntegerField(blank=True)),
                ('bicycle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ski_type', to='advertisement.BicycleType')),
            ],
            bases=('advertisement.advertisement',),
        ),
        migrations.AddField(
            model_name='images',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
