# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('ident', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('size', models.IntegerField()),
                ('bicycle_type', models.CharField(choices=[(b'rigid', b'\xd1\x80\xd0\xb8\xd0\xb3\xd0\xb8\xd0\xb4'), (b'hardtail', b'\xd1\x85\xd0\xb0\xd1\x80\xd0\xb4\xd1\x82\xd0\xb5\xd0\xb9\xd0\xbb'), (b'dvuhpodves', b'\xd0\xb4\xd0\xb2\xd1\x83\xd1\x85\xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb2\xd0\xb5\xd1\x81'), (b'city', b'\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'), (b'road', b'\xd1\x88\xd0\xbe\xd1\x81\xd1\x81\xd0\xb5\xd0\xb9\xd0\xbd\xd1\x8b\xd0\xb9'), (b'track', b'\xd1\x82\xd1\x80\xd0\xb5\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), (b'children', b'\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'), (b'bmx', b'BMX'), (b'skladnoj', b'\xd1\x81\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb9')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('ident', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('size', models.IntegerField()),
                ('for_weight', models.IntegerField(blank=True)),
                ('ski_type', models.CharField(choices=[(b'classic', b'\xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5'), (b'skate', b'\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8c\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb5'), (b'children', b'\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
