# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='ski',
            old_name='user',
            new_name='user_id',
        ),
    ]
