# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='bicycle_type',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='jumper_back',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='jumper_front',
        ),
    ]
