# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20180407_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='advertisement_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.Advertisement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ski',
            name='advertisement_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.Advertisement'),
            preserve_default=False,
        ),
    ]
