# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20180408_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='bicycle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_type', to='advertisement.BicycleType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bicycle',
            name='jumper_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_back', to='advertisement.BicycleJumper'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='jumper_front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_front', to='advertisement.BicycleJumper'),
        ),
    ]
