# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20180325_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='bicycle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_types', to='advertisement.BicycleType'),
        ),
    ]
