# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ident',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
