# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_auto_20180331_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleJumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='bicycle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_type', to='advertisement.BicycleType'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='jumper_front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_front', to='advertisement.BicycleJumper'),
        ),
    ]
