# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20180401_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='jumper_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumper_back', to='advertisement.BicycleJumper'),
        ),
    ]
