# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20180423_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='ski',
            name='ski_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ski_type', to='advertisement.SkiType'),
        ),
    ]
