# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20180311_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='bicycle_type',
            field=models.CharField(choices=[(b'rigid', b'rigid'), (b'hardtail', b'hardtail')], max_length=20),
        ),
    ]
