# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_bicycle_jumper_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='ident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ski',
            name='ident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
