# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20180507_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='advertisement',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
