# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=200, upload_to=b'image', width_field=100),
        ),
    ]
