# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_auto_20180311_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ski',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='advertisement_ptr',
        ),
        migrations.DeleteModel(
            name='Ski',
        ),
    ]
