# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_auto_20180406_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=b'media/image'),
        ),
    ]
