# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_auto_20180313_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.Advertisement')),
                ('size', models.IntegerField()),
                ('for_weight', models.IntegerField(blank=True)),
                ('ski_type', models.CharField(choices=[(b'classic', b'\xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5'), (b'skate', b'\xd0\xba\xd0\xbe\xd0\xbd\xd1\x8c\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb5'), (b'children', b'\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5')], max_length=20)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skis', to='advertisement.Advertisement')),
            ],
            bases=('advertisement.advertisement',),
        ),
    ]
