# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_ski'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='advertisement_ptr',
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='advertisement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.Advertisement'),
        ),
    ]
