# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_auto_20180513_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='transmission_back',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='transmission_front',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
    ]
