# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20161122_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=photos.models.get_image_filename, verbose_name='Image'),
        ),
    ]
