# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
