# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20180507_2000'),
        ('photos', '0006_auto_20180509_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advertisement.Advertisement'),
            preserve_default=False,
        ),
    ]
