# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='advertisement',
        ),
    ]
