# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=photos.models.get_image_filename),
        ),
    ]
