# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='note',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='milestone',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Race'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='milestone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.Milestone'),
            preserve_default=False,
        ),
    ]
