# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_auto_20180705_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='race.Milestone'),
        ),
    ]
